// The content of this file was generated by IBM Cloud
// No not modify it as it might get overridden


module.exports = function(app){
	//equire('./service-cloudant')(app, serviceManager);
	//require('./service-watson-conversation')(app, serviceManager);

};